FROM golang:latest

WORKDIR /usr/src/app

ENV COMMAND=api

ENV PORT=4000

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build ./cmd/${COMMAND}

EXPOSE ${PORT}

CMD /usr/src/app/${COMMAND}