FROM rust:alpine AS builder

WORKDIR /usr/src/app

RUN apk add --no-cache \
    protobuf \
    protobuf-dev \
    build-base \
    pkgconfig \
    git \
    curl


COPY . .

RUN cargo build --release

FROM debian:bullseye-slim AS runtime

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/grpc .

COPY --from=builder /usr/src/app/proto ./proto

RUN apt-get update && \
    apt-get install -y protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 3002

CMD ["./grpc"]
