// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Language string `json:"language"`
	Bio      string `json:"bio"`
	Version  int32  `json:"version"`
}

type Query struct {
}

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Language string `json:"language"`
	Bio      string `json:"bio"`
	Version  int32  `json:"version"`
}
