[package]
name = "graphql"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = { version = "4.11.0", features = ["openssl"] }
env_logger = "0.11.8"
juniper = "0.16.2"
log = "0.4.27"
openssl = "0.10.73"
