FROM rust:latest AS builder

ARG PORT=4000
ENV PORT=${PORT}

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim AS runtime

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/graphql .

COPY --from=builder  /usr/src/app/certs ./certs

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

EXPOSE $PORT

CMD ["./graphql"]