FROM caddy:alpine

COPY dist/ /var/www/html/
COPY Caddyfile /etc/caddy/Caddyfile

COPY certs/localhost/cert.pem /etc/caddy/ssl/cert.pem
COPY certs/localhost/key.pem /etc/caddy/ssl/key.pem

EXPOSE 443/udp
EXPOSE 443/tcp

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
