FROM nginx:alpine

COPY dist/ /usr/share/nginx/html/
COPY http2-docker.nginx.conf /etc/nginx/nginx.conf

COPY certs/localhost/cert.pem /etc/nginx/certs/cert.pem
COPY certs/localhost/key.pem /etc/nginx/certs/key.pem

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
