
FROM rust:latest AS builder

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim AS runtime

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/http1_1_api .

COPY --from=builder /usr/src/app/certs ./certs

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

EXPOSE 3004

CMD ["./http1_1_api"]
