[package]
name = "http_quic_api"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = "0.11.8"
rcgen = "0.14.3"
rustls = { version = "0.23.30", features = ["aws-lc-rs"] }
tokio = { version = "1.47.0", features = ["full", "sync"] }
