// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.6
// source: cmd/grpc/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cmd_grpc_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_grpc_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cmd_grpc_user_user_proto_rawDescGZIP(), []int{0}
}

type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_cmd_grpc_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_grpc_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_cmd_grpc_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessage) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserMessage) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UsersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserMessage         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersList) Reset() {
	*x = UsersList{}
	mi := &file_cmd_grpc_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersList) ProtoMessage() {}

func (x *UsersList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_grpc_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersList.ProtoReflect.Descriptor instead.
func (*UsersList) Descriptor() ([]byte, []int) {
	return file_cmd_grpc_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UsersList) GetUsers() []*UserMessage {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_cmd_grpc_user_user_proto protoreflect.FileDescriptor

const file_cmd_grpc_user_user_proto_rawDesc = "" +
	"\n" +
	"\x18cmd/grpc/user/user.proto\x12\x04user\"\a\n" +
	"\x05Empty\"y\n" +
	"\vUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"4\n" +
	"\tUsersList\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.user.UserMessageR\x05users2/\n" +
	"\x04User\x12'\n" +
	"\aUserRPC\x12\v.user.Empty\x1a\x0f.user.UsersListB\x14Z\x12cmd/grpc/user/userb\x06proto3"

var (
	file_cmd_grpc_user_user_proto_rawDescOnce sync.Once
	file_cmd_grpc_user_user_proto_rawDescData []byte
)

func file_cmd_grpc_user_user_proto_rawDescGZIP() []byte {
	file_cmd_grpc_user_user_proto_rawDescOnce.Do(func() {
		file_cmd_grpc_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_grpc_user_user_proto_rawDesc), len(file_cmd_grpc_user_user_proto_rawDesc)))
	})
	return file_cmd_grpc_user_user_proto_rawDescData
}

var file_cmd_grpc_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_grpc_user_user_proto_goTypes = []any{
	(*Empty)(nil),       // 0: user.Empty
	(*UserMessage)(nil), // 1: user.UserMessage
	(*UsersList)(nil),   // 2: user.UsersList
}
var file_cmd_grpc_user_user_proto_depIdxs = []int32{
	1, // 0: user.UsersList.users:type_name -> user.UserMessage
	0, // 1: user.User.UserRPC:input_type -> user.Empty
	2, // 2: user.User.UserRPC:output_type -> user.UsersList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_grpc_user_user_proto_init() }
func file_cmd_grpc_user_user_proto_init() {
	if File_cmd_grpc_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_grpc_user_user_proto_rawDesc), len(file_cmd_grpc_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_grpc_user_user_proto_goTypes,
		DependencyIndexes: file_cmd_grpc_user_user_proto_depIdxs,
		MessageInfos:      file_cmd_grpc_user_user_proto_msgTypes,
	}.Build()
	File_cmd_grpc_user_user_proto = out.File
	file_cmd_grpc_user_user_proto_goTypes = nil
	file_cmd_grpc_user_user_proto_depIdxs = nil
}
