FROM rust:bullseye AS builder

WORKDIR /usr/src/app

ARG API_PORT=3000

ARG GRPC_PORT=3002

ENV API_PORT=${API_PORT}

ENV GRPC_PORT=${GRPC_PORT}

ENV SQLX_OFFLINE=true

RUN apt-get update && \
    apt-get install -y \
    pkg-config \
    libssl-dev \
    protobuf-compiler \
    build-essential \
    git \
    curl

COPY . .

COPY ./.sqlx ./.sqlx

RUN cargo install sqlx-cli

RUN cargo build --release

FROM debian:bullseye-slim AS runtime

WORKDIR /app

COPY --from=builder /usr/src/app/certs ./certs

COPY --from=builder /usr/src/app/target/release/http .

COPY --from=builder /usr/src/app/proto ./proto

RUN apt-get update && \
    apt-get install -y protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

EXPOSE ${API_PORT} ${GRPC_PORT}

CMD ["./http"]
