[package]
name = "http3_api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.41"
proto = "0.1.2"
quinn = "0.11.8"
rustls = "0.23.29"
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-futures = "0.2.5"
